
a111:
    base_path: D:/BaiduNetdiskDownload/AI/SD0201

    checkpoints: D:/BaiduNetdiskDownload/AI/SD0201/models/Stable-diffusion
    configs: D:/BaiduNetdiskDownload/AI/SD0201/models/Stable-diffusion
    vae: D:/BaiduNetdiskDownload/AI/SD0201/models/VAE
    loras: D:/BaiduNetdiskDownload/AI/SD0201/models/Lora
    upscale_models: |
                  D:/BaiduNetdiskDownload/AI/SD0201/models/ESRGAN
                  D:/BaiduNetdiskDownload/AI/SD0201/models/SwinIR
    embeddings: D:/BaiduNetdiskDownload/AI/SD0201/embeddings
    controlnet: D:/BaiduNetdiskDownload/AI/SD0201/models/ControlNet
            
mycomfyui:
    base_path: D:/BaiduNetdiskDownload/AI
    checkpoints: D:/BaiduNetdiskDownload/AI/ComfyUImodels/checkpoints
    configs: D:/BaiduNetdiskDownload/AI/ComfyUImodels/configs
    loras: D:/BaiduNetdiskDownload/AI/ComfyUImodels/loras
    vae: D:/BaiduNetdiskDownload/AI/ComfyUImodels/vae
    clip: D:/BaiduNetdiskDownload/AI/ComfyUImodels/clip
    clip_vision: D:/BaiduNetdiskDownload/AI/ComfyUImodels/clip_vision
    style_models: D:/BaiduNetdiskDownload/AI/ComfyUImodels/style_models
    embeddings: D:/BaiduNetdiskDownload/AI/ComfyUImodels/embeddings
    diffusers: D:/BaiduNetdiskDownload/AI/ComfyUImodels/diffusers
    controlnet: D:/BaiduNetdiskDownload/AI/ComfyUImodels/controlnet
    gligen: D:/BaiduNetdiskDownload/AI/ComfyUImodels/gligen
    upscale_models: D:/BaiduNetdiskDownload/AI/ComfyUImodels/upscale_models
    hypernetworks: D:/BaiduNetdiskDownload/AI/ComfyUImodels/hypernetworks
    # custom_nodes: D:/BaiduNetdiskDownload/AI/custom_nodes
            