
a111:
    base_path: {}path/to/stable-diffusion-webui/

    checkpoints: {}models/Stable-diffusion
    configs: {}models/Stable-diffusion
    vae: {}models/VAE
    loras: {}models/Lora
    upscale_models: |
                  {}models/ESRGAN
                  {}models/SwinIR
    embeddings: {}embeddings
    controlnet: {}models/ControlNet
            